title: Site



columns:
  - width: 1/3
    sections:
      pages:
        type: pages
        templates:
          - objects
        headline: " "
        layout: cards
        size: large
#        status: listed
  - width: 2/3
    sections:
      home:
        type: pages
        templates:
          - default
        headline: " "
        layout: cards
        size: large
#        status: listed

  - width: 1/8
    sections:
      sectors:
        type: pages
        headline: " "
        template:
          - sectors
        layout: cards
        size: tiny
#        status: listed

  - width: 1/8
    sections:
      services:
        type: pages
        headline: " "
        template:
          - services
        layout: cards
        size: tiny
#        status: listed

  - width: 1/8
    sections:
      collaborators:
        type: pages
        headline: " "
        template:
          - collaborators
        layout: cards
        size: tiny
#        status: listed


  - width: 1/8
    sections:
      clients:
        type: pages
        headline: " "
        template:
          - clients
        layout: cards
        size: tiny
#        status: listed

